title: Tom Horak
url: 'https://tom-horak.de'
baseurl: '' #change it according to your repository name

#Profile information
name: Tom Horak
tagline: Ph.D. Student
affiliation: >
  Interactive Media Lab
  Technische Universität Dresden
pic: tom-horak.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: me@tom-horak.de
twitter: '@tomhorak21'
medium: '@tomhorak'
website: imld.de/~horak
scholar: https://scholar.google.de/citations?user=UpgjzPYAAAAJ&hl=en

collections:
  publications:
    output: true
    permalink: /publications/:path/

defaults:
  - scope:
      path: ""
      type: publications
    values:
      layout: publications

future: true